# SecretProviderClass for application configuration secrets
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: application-secrets
  namespace: default
spec:
  provider: aws
  parameters:
    region: us-east-1
    objects: |
      - objectName: "prod/app/config"
        objectType: "secretsmanager"
        objectVersionStage: "AWSCURRENT"
        jmesPath:
          - path: "encryption_key"
            objectAlias: "app_encryption_key"
          - path: "session_secret"
            objectAlias: "session_secret"
          - path: "oauth_client_secret"
            objectAlias: "oauth_client_secret"
      - objectName: "prod/app/certificates"
        objectType: "secretsmanager"
        objectVersionStage: "AWSCURRENT"
        jmesPath:
          - path: "tls_cert"
            objectAlias: "tls_certificate"
          - path: "tls_key"
            objectAlias: "tls_private_key"
          - path: "ca_cert"
            objectAlias: "ca_certificate"
  secretObjects:
    - secretName: application-config-secret
      type: Opaque
      data:
        - objectName: "app_encryption_key"
          key: "encryption-key"
        - objectName: "session_secret"
          key: "session-secret"
        - objectName: "oauth_client_secret"
          key: "oauth-client-secret"
    - secretName: application-tls-secret
      type: kubernetes.io/tls
      data:
        - objectName: "tls_certificate"
          key: "tls.crt"
        - objectName: "tls_private_key"
          key: "tls.key"
---
# SecretProviderClass for monitoring and observability secrets
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: monitoring-secrets
  namespace: monitoring
spec:
  provider: aws
  parameters:
    region: us-east-1
    objects: |
      - objectName: "prod/monitoring/grafana"
        objectType: "secretsmanager"
        objectVersionStage: "AWSCURRENT"
        jmesPath:
          - path: "admin_password"
            objectAlias: "grafana_admin_password"
          - path: "database_password"
            objectAlias: "grafana_db_password"
      - objectName: "prod/monitoring/prometheus"
        objectType: "secretsmanager"
        objectVersionStage: "AWSCURRENT"
        jmesPath:
          - path: "remote_write_token"
            objectAlias: "prometheus_remote_write_token"
          - path: "alertmanager_webhook"
            objectAlias: "alertmanager_webhook_url"
  secretObjects:
    - secretName: grafana-secret
      type: Opaque
      data:
        - objectName: "grafana_admin_password"
          key: "admin-password"
        - objectName: "grafana_db_password"
          key: "database-password"
    - secretName: prometheus-secret
      type: Opaque
      data:
        - objectName: "prometheus_remote_write_token"
          key: "remote-write-token"