# SecretProviderClass for database credentials with envelope encryption
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: database-secrets
  namespace: default
spec:
  provider: aws
  parameters:
    # AWS region where secrets are stored
    region: us-east-1
    # Secrets Manager secrets configuration
    objects: |
      - objectName: "prod/database/credentials"
        objectType: "secretsmanager"
        objectVersionStage: "AWSCURRENT"
        jmesPath:
          - path: "username"
            objectAlias: "db_username"
          - path: "password"
            objectAlias: "db_password"
          - path: "host"
            objectAlias: "db_host"
          - path: "port"
            objectAlias: "db_port"
      - objectName: "prod/database/ssl-cert"
        objectType: "secretsmanager"
        objectVersionStage: "AWSCURRENT"
        jmesPath:
          - path: "certificate"
            objectAlias: "db_ssl_cert"
          - path: "private_key"
            objectAlias: "db_ssl_key"
  # Optional: Create Kubernetes secrets for environment variable injection
  secretObjects:
    - secretName: database-secret
      type: Opaque
      data:
        - objectName: "db_username"
          key: "username"
        - objectName: "db_password"
          key: "password"
        - objectName: "db_host"
          key: "host"
        - objectName: "db_port"
          key: "port"
---
# SecretProviderClass for API keys and tokens
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: api-secrets
  namespace: default
spec:
  provider: aws
  parameters:
    region: us-east-1
    objects: |
      - objectName: "prod/api/external-service"
        objectType: "secretsmanager"
        objectVersionStage: "AWSCURRENT"
        jmesPath:
          - path: "api_key"
            objectAlias: "external_api_key"
          - path: "webhook_secret"
            objectAlias: "webhook_secret"
      - objectName: "prod/api/jwt-signing"
        objectType: "secretsmanager"
        objectVersionStage: "AWSCURRENT"
        jmesPath:
          - path: "private_key"
            objectAlias: "jwt_private_key"
          - path: "public_key"
            objectAlias: "jwt_public_key"
  secretObjects:
    - secretName: api-secret
      type: Opaque
      data:
        - objectName: "external_api_key"
          key: "api-key"
        - objectName: "webhook_secret"
          key: "webhook-secret"